---
- name: Install nginx
  dnf:
    name: nginx
    update_cache: yes
- name: Enable nginx
  service:
    name: nginx.service
    state: started
    enabled: yes
- name: Copy static files
  copy:
    src: ../../../../../src/frontend/build/
    dest: /usr/share/nginx/html/
  notify: restart nginx
- name: Add firewall port
  firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled