---
- name: Copy app files
  copy:
    src: "../../../../../src/backend/{{ item }}"
    dest: /home/opc/pythonapp/
    owner: opc
    group: opc
  with_items:
    - "wsgi.py"
    - "app.py"
    - "requirements.txt"
- name: Copy start bash script
  template:
    src: ../files/app.sh.j2
    dest: /home/opc/pythonapp/app.sh
    owner: opc
    group: opc
    mode: 0744
- name: Upgrade pip
  command: python3 -m pip install --upgrade pip
- name: Install dependencies
  command: python3 -m pip install -r /home/opc/pythonapp/requirements.txt
- name: FIXME probably not needed chown opc:opc for pythonapp and venv
  file:
    dest=/home/opc/pythonapp
    owner=opc
    group=opc
    recurse=yes
- name: Open firewall port
  firewalld:
    zone: public
    port: 3000/tcp
    permanent: yes
    immediate: yes
    state: enabled
- name: Copy app service unit
  copy:
    src: ../files/app.service
    dest: /etc/systemd/system/app.service
    mode: '0644'
- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes
- name: Start service App
  systemd:
    state: started
    name: app
- name: Enable service app
  systemd:
    name: app
    enabled: yes